SELECT
*
FROM 
	----- PERMISOS DE GRUPO -----
	(SELECT 
		DISTINCT (GNP.Id_Per)	AS [PERMISO_GRUPO],
		C.Id_Cli				AS [ID_CLIENTE],
		C.Cli_Nombre			AS [NOMBRE_CLIENTE]
	FROM 
					Tbl_Cliente			C
		INNER JOIN	Tbl_GpeNCli			GPNC	ON GPNC.Id_Cli = C.Id_Cli
		INNER JOIN	Tbl_GrupoPermisoWS	GP		ON GP.Id_Gpe = GPNC.Id_Gpe
		INNER JOIN	Tbl_GpeNPer			GNP		ON GNP.Id_Gpe = GP.Id_Gpe
	WHERE 1 = 1
		AND C.Cli_Activa = 1
		--AND C.Id_Cli = 74939
	) AS [PERMISOS DE GRUPO]
FULL JOIN
	----- PERMISOS DE CLIENTE -----
	(SELECT 
		PNC.Id_Per			AS [PERMISO_CLIENTE],
		C.Id_Cli			AS [ID_CLIENTE],
		C.Cli_Nombre		AS [NOMBRE_CLIENTE]
	FROM 
					Tbl_Cliente			C
		INNER JOIN	Tbl_PerNCli			PNC		ON PNC.Id_Cli = C.Id_Cli
	WHERE 1 = 1
		AND C.Cli_Activa = 1
		--AND C.Id_Cli = 74939
	) AS [PERMISOS DE CLIENTE]
ON	([PERMISOS DE GRUPO].ID_CLIENTE = [PERMISOS DE CLIENTE].ID_CLIENTE AND [PERMISOS DE GRUPO].PERMISO_GRUPO = [PERMISOS DE CLIENTE].PERMISO_CLIENTE)
WHERE
	1 = 1
	AND ([PERMISOS DE GRUPO].PERMISO_GRUPO IS NULL OR [PERMISOS DE CLIENTE].PERMISO_CLIENTE IS NULL)
