USE BD_Nincoming

/*DELARACIONES*/

	/*PROVEEDORES*/
	DECLARE @PROVS TABLE (PROV VARCHAR(10), NOMBRE VARCHAR(100));
	DECLARE @PROV AS varchar(10);

	/*SUPPLIER PUSH*/
	DECLARE @AVTW2M INT; SET @AVTW2M = 1;
	DECLARE @DYS INT; SET @DYS = 2;
	DECLARE @AVTB2C INT; SET @AVTB2C = 8;
	DECLARE @SUP INT;
	DECLARE @CLI VARCHAR (MAX);

	/*FICHAS EXTERNOS*/
	DECLARE @FICHAS_PROV TABLE (HOTELS VARCHAR(10));

	/*PRODUCTOS*/
	DECLARE @PRODUCTS_PUSH TABLE (RATE VARCHAR(30), ROOM VARCHAR(30));

	/*SEGMENTOS FICHAS SUPPLIER PUSH*/
	DECLARE @FICHAS_PROV_PUSH TABLE (HOTELS VARCHAR(10));

	/*SEGMENTOS ELEMENTOS*/
	DECLARE @ELEMENTS TABLE (ID_ELEMENT INT);
	DECLARE @ELEMENTS_PROV_PUSH TABLE (ID_ELEMENT INT);

	/*RECUENTOS*/
	DECLARE @COUNTELEMENTS TABLE (ELEMENTO VARCHAR(MAX),NUM_ELEMENT INT);

/*DEFINICION BASE*/
	/*PROVEEDORES*/
	INSERT INTO @PROVS
		SELECT
			Pai_Prov,
			CASE
				WHEN TPD_Nombre IS NULL THEN TPr_Nombre
				ELSE TPD_Nombre
			END AS Nombre
		FROM
						Tbl_ParametroIntegracion PI
			INNER JOIN	Tbl_ParametroIntegracionConfiguracion PIC ON PIC.Id_Pai = PI.Id_Pai
			LEFT JOIN	Tbl_TipoProductoDesglosado TPD ON TPD.id_TPD = PI.Pai_Prov
			LEFT JOIN	Tbl_TipoProducto TP ON TP.TPr_Tipo = PI.Pai_Prov
		WHERE 
			1 = 1
			AND PI.Pai_Codigo = 'SupPushModoDisponibilidad'
			AND PIC.Pic_Valor = 'Local'
	--SELECT * FROM @PROVS
/*POSIBLES EXTERNOS*/
/*
	SELECT * FROM @PROVS

	AVT		H2H - Avantio						--> TOTAL --> 6.990
	DYS9	HCC - Derbysoft Rotana				--> TOTAL --> 2.828.884		
	DYS7	HCC - Derbysoft Carlson				--> TOTAL --> 0	
	DYS6	HCC - Derbysoft Wyndham v4			--> TOTAL --> 138.000.000 
	DY20	HCC - Derbysoft Leonardo Hotels		--> TOTAL --> 0  
	DY18	HCC - Derbysoft IHG					--> TOTAL --> 30.000.000 
	DY22	HCC - Derbysotf Premier Inn			--> TOTAL --> 0 
	DY33	HCC - Derbysotf Choice				--> TOTAL --> 23.153  
	
	Avantio Apartments Demo
	J107
	W2M
	W2M DTP
*/


/*SELECCION SUPPLIER PUSH Y  PROVEEDOR EXTERNO*/
	SET @SUP = @DYS; --	@AVTW2M ; @DYS ; @AVTB2C
	SET @PROV = 'DYS6'
	SET @CLI = 'J107'
	SELECT * FROM @PROVS WHERE PROV = @PROV

/*DEFINICION FICHAS EXTERNAS*/
	/*FICHAS*/
	INSERT INTO @FICHAS_PROV
		SELECT DISTINCT(AlE_Cod) 
		FROM vwQlik_JP_Externos WITH (NOLOCK)
		WHERE AlE_Prov = @PROV
	SELECT COUNT(*) AS [FICHAS_PROV] FROM @FICHAS_PROV

/*DEFINICION FICHAS PUSH*/
	INSERT INTO @FICHAS_PROV_PUSH
		SELECT DISTINCT(SPE_CodHotel)
		FROM Tbl_AlojaSupplierPushElemento WITH (NOLOCK)
		WHERE 
		Id_SuP = @SUP
		--AND SPE_CodCliente = @CLI
		AND SPE_CodHotel IN (SELECT * FROM @FICHAS_PROV)
	SELECT COUNT(*) AS [FICHAS_PROV_PUSH] FROM @FICHAS_PROV_PUSH

/*DEFINICION ELEMENTOS PUSH*/
	INSERT INTO @ELEMENTS
	SELECT 
		Id_SPE
		FROM Tbl_AlojaSupplierPushElemento WITH (NOLOCK)
		WHERE SPE_CodHotel IN (SELECT * FROM @FICHAS_PROV_PUSH)
	SELECT COUNT(*) AS [ELEMENTS] FROM @ELEMENTS

/*RECUENTO PRODUCTOS*/
	--INSERT INTO @PRODUCTS_PUSH
	--	SELECT 
	--	DISTINCT SPE_RatePlanCode,SPE_CodigoHabitacion
	--	FROM Tbl_AlojaSupplierPushElemento WITH (NOLOCK)
	--	WHERE SPE_CodHotel IN (SELECT * FROM @FICHAS_PROV_PUSH)
	--SELECT COUNT(*) AS [PRODUCTS_PUSH] FROM @PRODUCTS_PUSH

/*RECUENTOS SUB ELEMENTOS PUSH*/

	/*ELEMENTOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Elemento',
		COUNT(*)  AS [Elemento]
	FROM		Tbl_AlojaSupplierPushElemento	ASPE
	INNER JOIN	@ELEMENTS						E		ON E.ID_ELEMENT = ASPE.Id_SPE

	/*CUPOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Cupos',
		COUNT(*) AS [Cupos]
	FROM		Tbl_AlojaSupplierPushCupo	ASPC
	INNER JOIN	@ELEMENTS					E		ON E.ID_ELEMENT = ASPC.Id_SPE

	/*PRECIOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Precios',
		COUNT(*) AS [Precios]
	FROM		Tbl_AlojaSupplierPushPrecio	ASPP
	INNER JOIN	@ELEMENTS					E		ON E.ID_ELEMENT = ASPP.Id_SPE

	/*PRECIOS NIÑOS*/
	--INSERT INTO @COUNTELEMENTS
	--SELECT 
	--	'Precios Niños',
	--	COUNT(*) AS [Precios Niños]
	--FROM		Tbl_AlojaSupplierPushPrecioNino ASPPN
	--INNER JOIN	Tbl_AlojaSupplierPushPrecio		ASPP	ON ASPP.Id_SPP = ASPPN.Id_SPP
	--INNER JOIN	@ELEMENTS						E		ON E.ID_ELEMENT = ASPP.Id_SPE

	/*NUEVO PRECIOS NIÑOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Nuevo Precios Niños',
		COUNT(*) AS [Nuevo Precios Niños]
	FROM		Tbl_AlojaSupplierPushPrecioNino							ASPPN
	INNER JOIN	Tbl_AlojaSupplierPushPrecioNAlojaSupplierPushPrecioNino	ASPP_ASPPN	ON ASPP_ASPPN.Id_SPN = ASPPN.Id_SPN
	INNER JOIN	Tbl_AlojaSupplierPushPrecio								ASPP		ON ASPP.Id_SPP = ASPP_ASPPN.Id_SPP
	INNER JOIN	@ELEMENTS												E			ON E.ID_ELEMENT = ASPP.Id_SPE

	SELECT * FROM  @COUNTELEMENTS

	/*RESTRICCIONES*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Restricciones',
		COUNT(*) AS [Restricciones]
	FROM		Tbl_AlojaSupplierPushRestriccion	ASPR
	INNER JOIN	@ELEMENTS							E		ON E.ID_ELEMENT = ASPR.Id_SPE

	/*POLITICAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas de Cancelación',
		COUNT(*) AS [Politicas de Cancelación]
	FROM		Tbl_AlojaSupplierPushPoliticaCancelacion	ASPPC
	INNER JOIN	@ELEMENTS									E		ON E.ID_ELEMENT = ASPPC.Id_SPE

	/*POLITICAS REGLAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas Reglas',
		COUNT(*) AS [Politicas Reglas]
	FROM		Tbl_AlojaSupplierPushPoliticaCancelacionRegla	ASPPCR
	INNER JOIN	Tbl_AlojaSupplierPushPoliticaCancelacion		ASPPC	ON ASPPC.Id_SPC = ASPPCR.Id_SPC
	INNER JOIN	@ELEMENTS										E		ON E.ID_ELEMENT = ASPPC.Id_SPE

	/*POLITICAS FECHAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas Fechas',
		COUNT(*) AS [Politicas Fechas]
	FROM		Tbl_AlojaSupplierPushPoliticaCancelacionFecha	ASPPCF
	INNER JOIN	Tbl_AlojaSupplierPushPoliticaCancelacion		ASPPC	ON ASPPC.Id_SPC = ASPPCF.Id_SPC
	INNER JOIN	@ELEMENTS										E		ON E.ID_ELEMENT = ASPPC.Id_SPE

/*TOTALES ELEMENTOS PUSH*/
	SELECT * FROM  @COUNTELEMENTS
	SELECT SUM(NUM_ELEMENT) AS [TOTAL_ELEMENTOS] FROM  @COUNTELEMENTS