USE BD_Nincoming

DECLARE @ETIQUETA_HOTEL_UNICO TABLE (Id_Etiqueta_UNICO INT, Orden_UNICO SMALLINT, Etiqueta_UNICO NVARCHAR(510), JP_UNICO CHAR(8));
DECLARE @ETIQUETA_HOTEL_PROPIO TABLE (Id_Etiqueta_PROPIO INT, Orden_PROPIO SMALLINT, Etiqueta_PROPIO NVARCHAR(510),HBE_PROPIO INT, JP_PROPIO CHAR(8));
DECLARE @ETIQUETA_HOTEL_GLOBAL TABLE (Id_Etiqueta_GLOBAL INT, Orden_GLOBAL SMALLINT, Etiqueta_GLOBAL NVARCHAR(510),HBE_GLOBAL INT, JP_GLOBAL CHAR(8));


SELECT 
	EAU.id_EAU		AS [Id_Etiqueta], 
	EAU.EAU_Orden	AS [Orden],
	INE.IEI_Desc	AS [Etiqueta]
FROM 
				Tbl_EtiquetaAlojaUnicoCliente	EAU		
	LEFT JOIN	Tbl_IdiNEtiqueta				INE		ON (EAU.id_EAU = INE.id_EAU AND INE.id_Idi = 'es')
ORDER BY
	Orden

/*ETIQUETAS POR HOTEL UNICO*/
INSERT INTO @ETIQUETA_HOTEL_UNICO
SELECT 
	EAU.id_EAU		AS [Id_Etiqueta],
	EAU.EAU_Orden	AS [Orden],
	INE.IEI_Desc	AS [Etiqueta],
	AUC.AUC_JPCode	AS [JP]
FROM 
				Tbl_AlojamientoUnicoCliente		AUC
	LEFT JOIN	Tbl_AucNEau						ANE		ON ANE.id_AUC = AUC.id_AUC
	LEFT JOIN	Tbl_EtiquetaAlojaUnicoCliente	EAU		ON EAU.id_EAU = ANE.id_EAU
	LEFT JOIN	Tbl_IdiNEtiqueta				INE		ON (EAU.id_EAU = INE.id_EAU AND INE.id_Idi = 'es')
WHERE 
	1 = 1
GROUP BY 
	EAU.id_EAU,
	EAU.EAU_Orden,
	INE.IEI_Desc,
	AUC.AUC_JPCode

/*ETIQUETAS POR HOTEL PROPIO*/
INSERT INTO @ETIQUETA_HOTEL_PROPIO
SELECT 
	EAU.id_EAU		AS [Id_Etiqueta], 
	EAU.EAU_Orden	AS [Orden],
	INE.IEI_Desc	AS [Etiqueta],
	A.Id_Alo		AS [HBE],
	AE.ALU_JPCode	AS [JP]
FROM 
				Tbl_Alojamiento					A
	LEFT JOIN	Tbl_EtiquetaAlojaUnicoCliente	EAU		ON EAU.id_EAU = A.id_EAU
	LEFT JOIN	Tbl_IdiNEtiqueta				INE		ON (EAU.id_EAU = INE.id_EAU AND INE.id_Idi = 'es')
	LEFT JOIN	vwQlik_JP_Externos				AE		ON (AE.AlE_Cod = A.Id_Alo AND AE.AlE_Prov = 'J107')
WHERE 
	1 = 1
	AND A.Alo_borrado = 0
GROUP BY 
	EAU.id_EAU,
	EAU.EAU_Orden,
	INE.IEI_Desc,
	A.Id_Alo,
	AE.ALU_JPCode

/*ETIQUETAS POR HOTEL GLOBAL*/
INSERT INTO @ETIQUETA_HOTEL_GLOBAL
SELECT 
	CASE
	WHEN EHU.Id_Etiqueta_UNICO IS NULL THEN EHP.Id_Etiqueta_PROPIO
	ELSE EHU.Id_Etiqueta_UNICO
	END															AS [ID ETIQUETA],
	CASE
	WHEN EHU.Orden_UNICO IS NULL THEN EHP.Orden_PROPIO
	ELSE EHU.Orden_UNICO
	END															AS [ORDEN],
	CASE
	WHEN EHU.Etiqueta_UNICO IS NULL THEN EHP.Etiqueta_PROPIO
	ELSE EHU.Etiqueta_UNICO
	END															AS [ETIQUETA],
	EHP.HBE_PROPIO												AS [HBE],
	EHU.JP_UNICO												AS [JP]
FROM
				@ETIQUETA_HOTEL_UNICO	EHU
	LEFT JOIN	@ETIQUETA_HOTEL_PROPIO	EHP	ON EHP.JP_PROPIO = EHU.JP_UNICO
WHERE
	1 = 1
	AND (EHU.Id_Etiqueta_UNICO IS NOT NULL OR EHP.Id_Etiqueta_PROPIO IS NOT NULL)  /*13124 ALGUNA ETIQUETA*/
	--AND (EHU.Id_Etiqueta_UNICO IS NULL AND EHP.Id_Etiqueta_PROPIO IS NULL)  /*147537 SIN ETIQUETAS*/
	--AND (EHU.Id_Etiqueta_UNICO <> EHP.Id_Etiqueta_PROPIO) /*ETIQUETA DISCREPANTE ENTRE HOTEL UNICO Y PROPIO. PREVALECE HOTEL UNICO*/
ORDER BY
	[ORDEN]


SELECT
	Id_Etiqueta_GLOBAL,
	Etiqueta_GLOBAL,
	Orden_GLOBAL,
	COUNT(*)
FROM
	@ETIQUETA_HOTEL_GLOBAL
GROUP BY
	Id_Etiqueta_GLOBAL,
	Etiqueta_GLOBAL,
	Orden_GLOBAL
ORDER BY
	Orden_GLOBAL

SELECT * FROM @ETIQUETA_HOTEL_GLOBAL ORDER BY Orden_GLOBAL

SELECT COUNT(*) FROM Tbl_AucNEau
