USE BD_Nincoming


/*DELARACIONES*/

	/*PROVEEDORES*/
	DECLARE @PROVS TABLE (PROV VARCHAR(10), NOMBRE VARCHAR(100));
	DECLARE @PROV AS varchar(10);

	/*SUPPLIER PUSH*/

	DECLARE @AVT INT; SET @AVT = 1;
	DECLARE @DYS INT; SET @DYS = 2;
	DECLARE @SUP INT;

	/*FICHAS EXTERNOS*/
	DECLARE @FICHAS_PROV_EXTERNO TABLE (HOTELS VARCHAR(10));

	/*MONGO*/
	DECLARE @ACTIVE_WYNDHAM_MONGO TABLE (HOTELS VARCHAR(10));

	/*SEGMENTOS FICHAS SUPPLIER PUSH*/
	DECLARE @PROV_PUSH TABLE (HOTELS VARCHAR(10));
	DECLARE @ACTIVE_MONGO_WYNDHAM_PUSH TABLE (HOTELS VARCHAR(10));
	DECLARE @INACTIVE_MONGO_WYNDHAM_PUSH TABLE (HOTELS VARCHAR(10));

	/*SEGMENTOS ELEMENTOS*/
	DECLARE @ELEMENTS TABLE (ID_ELEMENT INT);

	DECLARE @ELEMENTS_PROV_PUSH TABLE (ID_ELEMENT INT);
	DECLARE @ELEMENTS_ACTIVE_MONGO_WYNDHAM_PUSH TABLE (ID_ELEMENT INT);
	DECLARE @ELEMENTS_INACTIVE_MONGO_WYNDHAM_PUSH TABLE (ID_ELEMENT INT);

	/*RECUENTOS*/
	DECLARE @COUNTELEMENTS TABLE (ELEMENTO VARCHAR(MAX),NUM_ELEMENT INT);

/*RECUENTOS SUB ELEMENTOS PUSH*/

	/*PRECIOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Precios',
		COUNT(*) AS [Precios]
	FROM Tbl_AlojaSupplierPushPrecio WITH (NOLOCK)
	
	/*PRECIOS NIÑOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Precios Niños',
		COUNT(*) AS [Precios Niños]
	FROM Tbl_AlojaSupplierPushPrecioNino WITH (NOLOCK)
	WHERE Id_SPP IN 
					(
					SELECT Id_SPP
					FROM Tbl_AlojaSupplierPushPrecio WITH (NOLOCK)
					)

	/*POLITICAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas de Cancelación',
		COUNT(*) AS [Politicas de Cancelación]
	FROM Tbl_AlojaSupplierPushPoliticaCancelacion WITH (NOLOCK)

	/*POLITICAS REGLAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas Reglas',
		COUNT(*) AS [Politicas Reglas]
	FROM Tbl_AlojaSupplierPushPoliticaCancelacionRegla WITH (NOLOCK)
	WHERE Id_SPC IN (
					SELECT Id_SPC
					FROM Tbl_AlojaSupplierPushPoliticaCancelacion WITH (NOLOCK)
					)

	/*POLITICAS FECHAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas Fechas',
		COUNT(*) AS [Politicas Fechas]
	FROM Tbl_AlojaSupplierPushPoliticaCancelacionFecha WITH (NOLOCK)
	WHERE Id_SPC IN (
					SELECT Id_SPC
					FROM Tbl_AlojaSupplierPushPoliticaCancelacion WITH (NOLOCK)
					)

	/*RESTRICCIONES*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Restricciones',
		COUNT(*) AS [Restricciones]
	FROM Tbl_AlojaSupplierPushRestriccion WITH (NOLOCK)
	
	/*CUPOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Cupos',
		COUNT(*) AS [Cupos]
	FROM Tbl_AlojaSupplierPushCupo WITH (NOLOCK)

	/*ELEMENTOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Elemento',
		COUNT(*)  AS [Elemento]
	FROM Tbl_AlojaSupplierPushElemento  WITH (NOLOCK)

/*TOTALES ELEMENTOS PUSH*/
	SELECT * FROM  @COUNTELEMENTS
	SELECT SUM(NUM_ELEMENT) AS [TOTAL_ELEMENTOS] FROM  @COUNTELEMENTS