USE BD_Nincoming


/*DELARACIONES*/

	/*PROVEEDORES*/
	DECLARE @PROVS TABLE (PROV VARCHAR(10), NOMBRE VARCHAR(100));
	DECLARE @PROV AS varchar(10);

	/*SUPPLIER PUSH*/

	DECLARE @AVT INT; SET @AVT = 1;
	DECLARE @DYS INT; SET @DYS = 2;
	DECLARE @SUP INT;

	/*FICHAS EXTERNOS*/
	DECLARE @FICHAS_PROV_EXTERNO TABLE (HOTELS VARCHAR(10));

	/*MONGO*/
	DECLARE @ACTIVE_WYNDHAM_MONGO TABLE (HOTELS VARCHAR(10));

	/*SEGMENTOS FICHAS SUPPLIER PUSH*/
	DECLARE @PROV_PUSH TABLE (HOTELS VARCHAR(10));
	DECLARE @ACTIVE_MONGO_WYNDHAM_PUSH TABLE (HOTELS VARCHAR(10));
	DECLARE @INACTIVE_MONGO_WYNDHAM_PUSH TABLE (HOTELS VARCHAR(10));

	/*SEGMENTOS ELEMENTOS*/
	DECLARE @ELEMENTS TABLE (ID_ELEMENT INT);

	DECLARE @ELEMENTS_PROV_PUSH TABLE (ID_ELEMENT INT);
	DECLARE @ELEMENTS_ACTIVE_MONGO_WYNDHAM_PUSH TABLE (ID_ELEMENT INT);
	DECLARE @ELEMENTS_INACTIVE_MONGO_WYNDHAM_PUSH TABLE (ID_ELEMENT INT);

	/*RECUENTOS*/
	DECLARE @COUNTELEMENTS TABLE (ELEMENTO VARCHAR(MAX),NUM_ELEMENT INT);

/*DEFINICION BASE*/

	/*PROVEEDORES*/
	INSERT INTO @PROVS
		SELECT
			Pai_Prov,
			CASE
				WHEN TPD_Nombre IS NULL THEN TPr_Nombre
				ELSE TPD_Nombre
			END AS Nombre
		FROM
						Tbl_ParametroIntegracion PI
			INNER JOIN	Tbl_ParametroIntegracionConfiguracion PIC ON PIC.Id_Pai = PI.Id_Pai
			LEFT JOIN	Tbl_TipoProductoDesglosado TPD ON TPD.id_TPD = PI.Pai_Prov
			LEFT JOIN	Tbl_TipoProducto TP ON TP.TPr_Tipo = PI.Pai_Prov
		WHERE 
			1 = 1
			AND PI.Pai_Codigo = 'SupPushModoDisponibilidad'
			AND PIC.Pic_Valor = 'Local'

	/*POSIBLES EXTERNOS*/
	SELECT * FROM @PROVS

	/*SELECCION SUPPLIER PUSH Y  PROVEEDOR EXTERNO*/
	SET @SUP = @DYS; --	@AVT ; @DYS
	SET @PROV = 'DYS9'
	SELECT * FROM @PROVS WHERE PROV = @PROV

/*DEFINICION FICHAS EXTERNAS*/

	/*FICHAS*/
	INSERT INTO @FICHAS_PROV_EXTERNO
		SELECT DISTINCT(AlE_Cod) 
		FROM vwQlik_JP_Externos WITH (NOLOCK)
		WHERE AlE_Prov = @PROV
	SELECT COUNT(*) AS [FICHAS_PROV_EXTERNO] FROM @FICHAS_PROV_EXTERNO


/*DEFINICION FICHAS PUSH*/

	INSERT INTO @PROV_PUSH
		SELECT DISTINCT(SPE_CodHotel)
		FROM Tbl_AlojaSupplierPushElemento WITH (NOLOCK)
		WHERE 
		Id_SuP = @SUP
		AND SPE_CodHotel IN (SELECT * FROM @FICHAS_PROV_EXTERNO)
	SELECT COUNT(*) AS [PROV_EXTERNO_PUSH] FROM @PROV_PUSH

/*DEFINICION ELEMENTOS PUSH*/

	INSERT INTO @ELEMENTS
	--INSERT INTO @ELEMENTS_PROV_PUSH
		SELECT Id_SPE
		FROM Tbl_AlojaSupplierPushElemento WITH (NOLOCK)
		WHERE SPE_CodHotel IN (SELECT * FROM @PROV_PUSH)


/*RECUENTOS SUB ELEMENTOS PUSH*/

	/*PRECIOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Precios',
		COUNT(*) AS [Precios]
	FROM Tbl_AlojaSupplierPushPrecio WITH (NOLOCK)
	WHERE Id_SPE IN (SELECT * FROM @ELEMENTS) 
	
	/*PRECIOS NIÑOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Precios Niños',
		COUNT(*) AS [Precios Niños]
	FROM Tbl_AlojaSupplierPushPrecioNino WITH (NOLOCK)
	WHERE Id_SPP IN 
					(
					SELECT Id_SPP
					FROM Tbl_AlojaSupplierPushPrecio WITH (NOLOCK)
					WHERE Id_SPE IN (SELECT * FROM @ELEMENTS) 
					)

	/*POLITICAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas de Cancelación',
		COUNT(*) AS [Politicas de Cancelación]
	FROM Tbl_AlojaSupplierPushPoliticaCancelacion WITH (NOLOCK)
	WHERE Id_SPE IN (SELECT * FROM @ELEMENTS)

	/*POLITICAS REGLAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas Reglas',
		COUNT(*) AS [Politicas Reglas]
	FROM Tbl_AlojaSupplierPushPoliticaCancelacionRegla WITH (NOLOCK)
	WHERE Id_SPC IN (
					SELECT Id_SPC
					FROM Tbl_AlojaSupplierPushPoliticaCancelacion WITH (NOLOCK)
					WHERE Id_SPE IN (SELECT * FROM @ELEMENTS)  
					)

	/*POLITICAS FECHAS*/
	INSERT INTO @COUNTELEMENTS
	SELECT 
		'Politicas Fechas',
		COUNT(*) AS [Politicas Fechas]
	FROM Tbl_AlojaSupplierPushPoliticaCancelacionFecha WITH (NOLOCK)
	WHERE Id_SPC IN (
					SELECT Id_SPC
					FROM Tbl_AlojaSupplierPushPoliticaCancelacion WITH (NOLOCK)
					WHERE Id_SPE IN (SELECT * FROM @ELEMENTS)  
					)

	/*ELEMENTOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Elemento',
		COUNT(*)  AS [Elemento]
	FROM Tbl_AlojaSupplierPushElemento  WITH (NOLOCK)
	WHERE Id_SPE IN (SELECT * FROM @ELEMENTS)

	/*CUPOS*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Cupos',
		COUNT(*) AS [Cupos]
	FROM Tbl_AlojaSupplierPushCupo WITH (NOLOCK)
	WHERE Id_SPE IN (SELECT * FROM @ELEMENTS) 

	/*RESTRICCIONES*/
	INSERT INTO @COUNTELEMENTS
	SELECT
		'Restricciones',
		COUNT(*) AS [Restricciones]
	FROM Tbl_AlojaSupplierPushRestriccion WITH (NOLOCK)
	WHERE Id_SPE IN (SELECT * FROM @ELEMENTS) 

/*TOTALES ELEMENTOS PUSH*/
	SELECT * FROM  @COUNTELEMENTS
	SELECT SUM(NUM_ELEMENT) AS [TOTAL_ELEMENTOS] FROM  @COUNTELEMENTS