SELECT 

DISTINCT 
A.ID_Alo,
INA.IAl_Nombre
--HAB.id_alo			ID_ALO,
--HAB.id_tha			ID_THA_HIJA,
--INANT.IAN_Nombre	NOM_THA_HIJA,
--HAB.Id_THa_Master	ID_THA_MASTER,
--INANTMAST.IAN_Nombre NOM_THA_MASTER
--HABMAST.id_alo,
--HABMAST.id_tha,
--HABMAST.Id_THa_Master,
--HABMASTNOM.ITH_Nombre,


FROM 
			Tbl_AloNTHa		HAB

INNER JOIN	Tbl_Alojamiento A ON A.Id_Alo = HAB.Id_Alo AND A.Alo_borrado = 0
INNER JOIN	Tbl_IDiNAlo		INA ON INA.Id_Alo = a.Id_Alo AND INA.Id_Idi = 'ES'
INNER JOIN	Tbl_IdiNTHa 	HABNOM		ON HABNOM.Id_THa = HAB.Id_THa AND HABNOM.Id_Idi = 'ES'
INNER JOIN	Tbl_IDiNANT		INANT		ON INANT.Id_Ant = HAB.id_Ant AND INANT.Id_Idi = 'ES'
INNER JOIN	Tbl_AloNTHa		HABMAST 	ON HABMAST.Id_THa = HAB.Id_THa_Master
INNER JOIN	Tbl_IdiNTHa 	HABMASTNOM	ON HABMASTNOM.Id_THa = HABMAST.Id_THa AND HABMASTNOM.Id_Idi = 'ES'
INNER JOIN	Tbl_IDiNANT		INANTMAST	ON INANTMAST.Id_Ant = HABMAST.id_Ant AND INANTMAST.Id_Idi = 'ES'

WHERE
	1 = 1
	AND HAB.Ant_Activa = 1
	AND HAB.ANT_Eliminada = 0
	AND HABMAST.Ant_Activa = 1
	AND HABMAST.ANT_Eliminada = 0
	--AND HAB.ID_ALO = 23338--20373
	--AND HABMAST.ID_ALO = 23338--20373
	AND HAB.Id_THa_Master IS NOT NULL 
	--AND HAB.Id_THa = 888



--> 888 (HIJA) --> 366		(MASTER)
--> 339 (HIJA) --> 1530		(MASTER)


