USE BD_Nincoming
SELECT	
	IPs_CLI.[ID_AGENCIA],
	IPs_CLI.[AGENCIA],
	IPs_CLI.[ID_INTEGRADOR_AGENCIA],
	IPs_CLI.[INTEGRADOR_AGENCIA],
	IPs_CLI.[IP_AGENCIA],
	IPs_INT.[INTEGRADOR],
	IPs_INT.[ID_INTEGRADOR],
	IPs_INT.[IP_INTEGRADOR]
FROM	(
		SELECT 
			IWS.Int_Nombre																		AS [INTEGRADOR],
			LIPI.LIP_IdUsuario																	AS [ID_INTEGRADOR],
			LIPI.LIP_TipoUsuario																AS [IP_TYPE],
			LIPI.LIP_DirIP																		AS [DEC_IP_INTEGRADOR],
			CONVERT(VARCHAR(MAX),CONVERT(BIGINT,LIPI.LIP_DirIP/256/256/256) % 256) + '.' + 
			CONVERT(VARCHAR(MAX),CONVERT(BIGINT,LIPI.LIP_DirIP/256/256) % 256) + '.' + 
			CONVERT(VARCHAR(MAX),CONVERT(BIGINT,LIPI.LIP_DirIP/256) % 256) + '.' + 
			CONVERT(VARCHAR(MAX),CONVERT(BIGINT,LIPI.LIP_DirIP) % 256)							AS [IP_INTEGRADOR]
		FROM
						Tbl_IntegradorWS	IWS
			INNER JOIN	Tbl_ListaIPs		LIPI	ON (LIPI.LIP_IdUsuario = IWS.Id_Int AND LIPI.LIP_TipoUsuario = 'Int')
		)	AS [IPs_INT]
		FULL JOIN
		(
		SELECT 
			C.Cli_Nombre																		AS [AGENCIA],
			C.Id_Cli																			AS [ID_AGENCIA],
			IWS.Int_Nombre																		AS [INTEGRADOR_AGENCIA],
			IWS.Id_Int																			AS [ID_INTEGRADOR_AGENCIA],
			LIPC.LIP_TipoUsuario																AS [IP_TYPE],
			LIPC.LIP_DirIP																		AS [DEC_IP_AGENCIA],
			CONVERT(VARCHAR(MAX),CONVERT(BIGINT,LIPC.LIP_DirIP/256/256/256) % 256) + '.' + 
			CONVERT(VARCHAR(MAX),CONVERT(BIGINT,LIPC.LIP_DirIP/256/256) % 256) + '.' + 
			CONVERT(VARCHAR(MAX),CONVERT(BIGINT,LIPC.LIP_DirIP/256) % 256) + '.' + 
			CONVERT(VARCHAR(MAX),CONVERT(BIGINT,LIPC.LIP_DirIP) % 256)							AS [IP_AGENCIA]
		FROM
						Tbl_Cliente			C
			INNER JOIN	Tbl_IntegradorWS	IWS		ON IWS.Id_Int = C.Id_Int
			INNER JOIN	Tbl_ListaIPs		LIPC	ON (LIPC.LIP_IdUsuario = C.Id_Cli AND LIPC.LIP_TipoUsuario = 'Cli')
		GROUP BY
			C.Cli_Nombre,
			C.Id_Cli,
			IWS.Int_Nombre,
			IWS.Id_Int,
			LIPC.LIP_IdUsuario,
			LIPC.LIP_TipoUsuario,
			LIPC.LIP_DirIP
		)	AS [IPs_CLI]	ON [IPs_CLI].[IP_AGENCIA] = [IPs_INT].[IP_INTEGRADOR] --AND [IPs_CLI].[ID_INTEGRADOR_AGENCIA] = [IPs_INT].[IP_INTEGRADOR]
WHERE
	1 = 1
--IPS QUE NO CORRESPONDEN AL INTEGRADOR ASOCIADO
	AND	(
		[IPs_INT].[ID_INTEGRADOR] <> [IPs_CLI].[ID_INTEGRADOR_AGENCIA] 
		OR [IPs_INT].[IP_INTEGRADOR] IS NULL
		)
	--AND [IPs_CLI].[AGENCIA] = 'AZULMARINO CENTRAL'
	--AND	(
	--	[IPs_INT].[IP_INTEGRADOR] IS NULL 
	--	OR [IPs_INT].[IP_INTEGRADOR] = [IPs_CLI].[IP_AGENCIA]
	--	)

	AND [IPs_INT].[ID_INTEGRADOR] IS NULL 

	--AND [IPs_CLI].[AGENCIA] = 'AZULMARINO VIAJES W2M SA (CENTRAL)'

--RANGO IPS PRIVADAS
	--AND	(	
	--		([IPs_CLI].[DEC_IP_AGENCIA] BETWEEN 167772160 AND 184549375)	-- Clase A
	--	OR	([IPs_CLI].[DEC_IP_AGENCIA] BETWEEN 2886729728 AND 2886792191)	-- Clase B
	--	OR	([IPs_CLI].[DEC_IP_AGENCIA] BETWEEN 3232235520 AND 3232301055)	-- Clase C
	--	OR	([IPs_CLI].[DEC_IP_AGENCIA] BETWEEN 2847802880 AND 2847867392)	-- APIPA
	--	)

GROUP BY
	[IPs_CLI].[ID_AGENCIA],
	[IPs_CLI].[AGENCIA],
	[IPs_CLI].[ID_INTEGRADOR_AGENCIA],
	[IPs_CLI].[INTEGRADOR_AGENCIA],
	[IPs_CLI].[IP_AGENCIA],
	[IPs_INT].[INTEGRADOR],
	[IPs_INT].[ID_INTEGRADOR],
	[IPs_INT].[IP_INTEGRADOR]
ORDER BY
	[IPs_CLI].[INTEGRADOR_AGENCIA],
	[IPs_CLI].[ID_AGENCIA],
	[IPs_CLI].[IP_AGENCIA]
