USE BD_Nincoming

/*DELARACIONES*/

	/*PROVEEDORES*/
	DECLARE @PROVS TABLE (PROV VARCHAR(10), NOMBRE VARCHAR(100));
	DECLARE @PROV AS varchar(10);

	/*SUPPLIER PUSH*/
	DECLARE @DYS INT; SET @DYS = 2;
	DECLARE @SUP INT;

	/*FICHAS EXTERNOS*/
	DECLARE @FICHAS_PROV TABLE (HOTELS VARCHAR(10));

	/*PRODUCTOS*/
	DECLARE @PRODUCTS_PUSH TABLE (ALO VARCHAR(30), RATE VARCHAR(30), ROOM VARCHAR(30));

	/*SEGMENTOS FICHAS SUPPLIER PUSH*/
	DECLARE @FICHAS_PROV_PUSH TABLE (HOTELS VARCHAR(10));

	/*SEGMENTOS ELEMENTOS*/
	DECLARE @ELEMENTS TABLE (ID_ELEMENT INT);
	DECLARE @ELEMENTS_PROV_PUSH TABLE (ID_ELEMENT INT);

	/*RECUENTOS*/
	DECLARE @COUNTELEMENTS TABLE (ELEMENTO VARCHAR(MAX),NUM_ELEMENT INT);

/*DEFINICION BASE*/
	/*PROVEEDORES*/
	INSERT INTO @PROVS
		SELECT
			Pai_Prov,
			CASE
				WHEN TPD_Nombre IS NULL THEN TPr_Nombre
				ELSE TPD_Nombre
			END AS Nombre
		FROM
						Tbl_ParametroIntegracion PI
			INNER JOIN	Tbl_ParametroIntegracionConfiguracion PIC ON PIC.Id_Pai = PI.Id_Pai
			LEFT JOIN	Tbl_TipoProductoDesglosado TPD ON TPD.id_TPD = PI.Pai_Prov
			LEFT JOIN	Tbl_TipoProducto TP ON TP.TPr_Tipo = PI.Pai_Prov
		WHERE 
			1 = 1
			AND PI.Pai_Codigo = 'SupPushModoDisponibilidad'
			AND PIC.Pic_Valor = 'Local'
	--SELECT * FROM @PROVS

/*SELECCION SUPPLIER PUSH Y  PROVEEDOR EXTERNO*/
	SET @SUP = @DYS; --	@AVTW2M ; @DYS ; @AVTB2C
	SET @PROV = 'DYS6'
	SELECT * FROM @PROVS WHERE PROV = @PROV

/*DEFINICION FICHAS EXTERNAS*/
	/*FICHAS*/
	INSERT INTO @FICHAS_PROV
		SELECT DISTINCT(AlE_Cod) 
		FROM vwQlik_JP_Externos WITH (NOLOCK)
		WHERE AlE_Prov = @PROV
	SELECT COUNT(*) AS [FICHAS_PROV] FROM @FICHAS_PROV

/*DEFINICION FICHAS PUSH*/
	INSERT INTO @FICHAS_PROV_PUSH
		SELECT DISTINCT(SPE_CodHotel)
		FROM Tbl_AlojaSupplierPushElemento WITH (NOLOCK)
		WHERE 
		Id_SuP = @SUP
		--AND SPE_CodCliente = @CLI
		AND SPE_CodHotel IN (SELECT * FROM @FICHAS_PROV)
	SELECT COUNT(*) AS [FICHAS_PROV_PUSH] FROM @FICHAS_PROV_PUSH

/*RECUENTO PRODUCTOS*/
	INSERT INTO @PRODUCTS_PUSH
		SELECT 
		DISTINCT SPE_CodHotel,SPE_RatePlanCode,SPE_CodigoHabitacion
		FROM Tbl_AlojaSupplierPushElemento WITH (NOLOCK)
		WHERE SPE_CodHotel IN (SELECT * FROM @FICHAS_PROV_PUSH)
	SELECT COUNT(*) AS [PRODUCTS_PUSH] FROM @PRODUCTS_PUSH