USE BD_Nincoming

DECLARE @HOTELES2025 TABLE (HOTEL nvarchar(240), NUM_RES INT);
DECLARE @PRODUCTO_X_HOTEL TABLE (ALO NVARCHAR(240),LRE INT, ROOM VARCHAR(100), RATE VARCHAR(100));


INSERT INTO @HOTELES2025
	SELECT 
	RAE_AlojaID,
	COUNT(Id_LRe) AS [NUM RES]
	FROM TBL_ReservaAlojamientoExterno 
	WHERE RAE_TipoProducto = 'DYS6' AND (Feccre BETWEEN '2025-03-31' AND '2025-07-31')
	GROUP BY RAE_AlojaID
	ORDER BY [NUM RES] DESC

SELECT COUNT(HOTEL) NUM_HOTELS_2025, SUM(NUM_RES) NUM_RES_2025 FROM @HOTELES2025

INSERT INTO @PRODUCTO_X_HOTEL
	SELECT 
		RAE_AlojaID,
		Id_LRe,
		CAST(RAE_ReservaExterna AS XML).value('(XML/RoomTypeCode)[1]', 'VARCHAR(MAX)')			AS [RoomTypeCode],
		CAST(RAE_ReservaExterna AS XML).value('(XML/RatePlanCode)[1]', 'VARCHAR(MAX)')			AS [RatePlanCode]
	FROM TBL_ReservaAlojamientoExterno 
	WHERE RAE_TipoProducto = 'DYS6' AND (Feccre BETWEEN '2025-03-31' AND '2025-07-31')

SELECT DISTINCT ALO,ROOM,RATE,COUNT (LRE) AS CUENTA
FROM @PRODUCTO_X_HOTEL
WHERE ALO = '80388'
GROUP BY ALO,ROOM,RATE
ORDER BY CUENTA DESC

SELECT DISTINCT ALO,ROOM,RATE,COUNT (LRE) AS CUENTA
FROM @PRODUCTO_X_HOTEL
GROUP BY ALO,ROOM,RATE
ORDER BY CUENTA DESC