--CopiasPMI.db.jun.db.jun
USE BD_Nincoming_1043630_JBausa_20250101

DECLARE @HOTELES2024 TABLE (HOTEL nvarchar(240), NUM_RES INT);
DECLARE @PRODUCTO_X_HOTEL TABLE (ALO NVARCHAR(240),LRE INT, ROOM VARCHAR(100), RATE VARCHAR(100));

INSERT INTO @HOTELES2024
	SELECT 
	RAE_AlojaID,
	COUNT(Id_LRe) AS [NUM RES]
	FROM TBL_ReservaAlojamientoExterno 
	WHERE RAE_TipoProducto = 'DYS6' AND (Feccre BETWEEN '2024-01-01' AND '2025-01-01')
	GROUP BY RAE_AlojaID
	ORDER BY [NUM RES] DESC

SELECT COUNT(HOTEL) NUM_HOTELS_2024, SUM(NUM_RES) NUM_RES_2024 FROM @HOTELES2024

INSERT INTO @PRODUCTO_X_HOTEL
	SELECT 
		RAE_AlojaID,
		Id_LRe,
		CAST(RAE_ReservaExterna AS XML).value('(XML/RoomTypeCode)[1]', 'VARCHAR(MAX)')			AS [RoomTypeCode],
		CAST(RAE_ReservaExterna AS XML).value('(XML/RatePlanCode)[1]', 'VARCHAR(MAX)')			AS [RatePlanCode]
	FROM TBL_ReservaAlojamientoExterno 
	WHERE RAE_TipoProducto = 'DYS6' AND (Feccre BETWEEN '2024-01-01' AND '2025-01-01')

SELECT DISTINCT ALO,ROOM,RATE,COUNT (LRE) AS CUENTA
FROM @PRODUCTO_X_HOTEL
WHERE ALO = '80388'
GROUP BY ALO,ROOM,RATE
ORDER BY CUENTA DESC

SELECT DISTINCT ALO,ROOM,RATE,COUNT (LRE) AS CUENTA
FROM @PRODUCTO_X_HOTEL
GROUP BY ALO,ROOM,RATE
ORDER BY CUENTA DESC