WITH RQ_X_HORA AS (
				SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_01 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_02 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_03 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_04 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_05 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_06 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_07 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_08 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_09 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
	UNION ALL	SELECT DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0) AS HoraDelDia, COUNT(*) AS Conteo FROM Tbl_AlojaSupplierPushQueue_10 GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, FecCre), 0)
)

SELECT HoraDelDia,SUM(Conteo) AS RQs FROM RQ_X_HORA GROUP BY HoraDelDia ORDER BY HoraDelDia